@startuml water_state
hide empty description

state standby {
  standby: feed off
  standby: pump off
  standby: purge on
}

state running {
  running : feed on
  running : purge off
  running : pump on
}

state prime {
  prime : feed on
  prime : purge on
  prime : pump off
}

state rinse_start {
  rinse_start : feed on
  rinse_start : purge on 
  rinse_start : pump on
}
state rinse_stop {
  rinse_stop : feed on
  rinse_stop : purge on 
  rinse_stop : pump on
}

[*] --> standby : start
standby --> prime : touch_play
prime --> rinse_start : t_prime
rinse_start --> running : t_rinse_start
running --> rinse_stop : touch_pause
rinse_stop --> standby : t_rinse_stop
running --> rinse_start : t_run

@enduml