@startuml water_state
hide empty description

state standby {
  standby: feed off
  standby: pump off
  standby: purge on
}

state running {
  running : feed on
  running : purge off
  running : pump on
}

state prime {
  prime : feed on
  prime : purge on
  prime : pump off
}

state rinse {
  rinse : feed on
  rinse : purge on 
  rinse : pump on
}

[*] --> standby
standby --> prime : touch_play
prime --> rinse : t_prime
rinse --> running : t_rinse_start
running --> rinse : touch_pause
rinse --> standby : t_rinse_stop
running --> rinse : t_run

@enduml