@startuml water_state
hide empty description

state waiting {
  waiting: feed\t\toff
  waiting: pump\toff
  waiting: purge\ton
  waiting: btn\t\tpause
  waiting: /wait rinse_period
}

state priming {
  priming : feed\t\ton
  priming : purge\ton
  priming : pump\toff
  priming : /wait prime_time
}

state rinsing {
    rinsing: feed\t\ton
    rinsing: purge\ton 
    rinsing: pump\ton
    rinsing: /wait rinse_time
}

state running {
  running: feed\t\ton
  running: purge\toff
  running: pump\ton
  running: btn\t\tplay
  running: /wait run_time
}

state stopstart <<choice>>
[*] --> waiting : start
waiting --> priming : rinse_needed
waiting --> priming : btn_pressed\n[btn = play]
priming --> rinsing: primed
rinsing --> stopstart: rinsed
stopstart --> running : [btn == play]
running --> rinsing: btn_pressed\n[btn = pause]
stopstart--> waiting : [btn == pause]
running --> rinsing: run_time

@enduml